# snyk.ini — managed by alaya-snyk-importer
# Edit values below and merge the PR to update Snyk project attributes.
# Re-run import-all to sync changes to Snyk.

[AlayaCare/keycloak-user-migration:docker/e2e/package.json]
enabled = false
business_criticality = medium
environment = frontend
lifecycle = production
tags = team:Raccoons

[AlayaCare/keycloak-user-migration:docker/legacy-system-example/pom.xml]
enabled = true
business_criticality = medium
environment = backend
lifecycle = production
tags = team:Raccoons

[AlayaCare/keycloak-user-migration:pom.xml]
enabled = true
business_criticality = medium
environment = backend
lifecycle = production
tags = team:Raccoons
