version: '3.2'

services:
  keycloak:
    build:
      context: ../
      dockerfile: docker/keycloak/Dockerfile
      args:
        - KEYCLOAK_IMAGE=${KEYCLOAK_IMAGE}
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8024:8080"
    networks:
      - internal

  legacy-system-example:
    build:
      context: legacy-system-example
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - internal

networks:
  internal: